spring.application.name=practice2
spring.datasource.url=jdbc:mysql://localhost:3306/springSecurity
spring.datasource.username=root
spring.datasource.password=bipin2065.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasourse.driven-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.security.user.name=bipin
#spring.security.user.password=bipin123
